# Generated by Django 5.0 on 2023-12-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='task',
            new_name='main_task_id',
        ),
    ]
