# Generated by Django 5.0 on 2023-12-21 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_task_subtask_main_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='main_task_id',
            new_name='main_task',
        ),
    ]
